name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t dockr-app-mail:ci .

      # Step 4: Start Mailhog container
      - name: Start Mailhog
        run: docker run -d -p 1025:1025 -p 8025:8025 mailhog/mailhog

      # Step 5: Run Spring Boot container
      - name: Run Spring Boot app
        run: docker run -d -p 8080:8080 dockr-app-mail:ci

      # Step 6: Wait for app to start
      - name: Wait for Spring Boot
        run: |
          echo "Waiting for app to be ready..."
          sleep 20

      # Step 7: Run tests
      - name: Run Tests
        run: |
          docker exec $(docker ps -q -f ancestor=dockr-app-mail:ci) ./mvnw test || mvn test
