name: Docker CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 3: Set up Maven (optional if using ./mvnw in Docker)
      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Step 4: Set up Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 5: Build Docker image
      - name: Build Docker image
        run: docker build -t dockr-app-mail:ci .

      # Step 6: Start Mailhog container
      - name: Start Mailhog
        run: docker run -d -p 1025:1025 -p 8025:8025 mailhog/mailhog

      # Step 7: Run Spring Boot container
      - name: Run Spring Boot app
        run: docker run -d -p 8080:8080 dockr-app-mail:ci

      # Step 8: Wait for app to start
      - name: Wait for Spring Boot
        run: |
          echo "Waiting for app to be ready..."
          for i in {1..15}; do
            curl -s http://localhost:8080/hello && break
            echo "Waiting..."
            sleep 2
          done

      # Step 9: Run tests
      - name: Run Tests
        run: |
          docker exec $(docker ps -q -f ancestor=dockr-app-mail:ci) ./mvnw test || mvn test
